---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./nginx-config.yaml
  - ./volumes.yaml
  - ./sentieri-webapp.secret.yaml
  - ./sentieri-webapp.yaml
