apiVersion: ENC[AES256_GCM,data:anI=,iv:81YufVEim5vvMNpzF2ozJIGRhvNHsm56IjMe6mmKCKA=,tag:XHznYmgP+gzhpZjg7oXHcg==,type:str]
kind: ENC[AES256_GCM,data:qqyKlmxN,iv:VtVLV5jOHXIZ1FBmMgeouh1OxjtyhZDfg+G9hyjkulE=,tag:VFM2u0wHqVtyxXgPk2QoUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BdjIXtMhlFZdyRnRuXLaVC3j1kc=,iv:ndvHR4vNAEkQOtoEs0eWjNajdDK5Top9ZYE6/CcUg78=,tag:pptX+yd9PPxlUwrYAiIoyg==,type:str]
    namespace: ENC[AES256_GCM,data:BIt2dWDrLoP7SmD/DPSC,iv:bPKnnETonZd8TjRN8EE1Z1X4KzTMOmDt5dlHYoC3Sd8=,tag:pH6lKCAwJYKW3CcfyM1yww==,type:str]
type: ENC[AES256_GCM,data:vxnvkUXD,iv:UGbqTs7oYXrkJbv8Fcj2fILQqAitMVqNrEkw6dls0A8=,tag:4fCnMXRIvMH3erMB6qh6mg==,type:str]
stringData:
    .htpasswd-ricerche-sentieri: ENC[AES256_GCM,data:6j5JQVkks+skCyFZ+OMI04vuWP+mNVqYVJCKtQAhViQNQYNdppN6Jis/jWcgLJHY6AXZQ0aJ7xFm0L+jen9sKRhY0LtefwTZj1YW9RkOtrNaiqCfJxDAo0ivbbD6bEi1bhC20CsD+BdhdeU6RfzRPYhCWtBiv8l7/JsdIZdugs9CUWYvnceYg/yCPWNPS6jQlEI8wdxgqUCjwVqddIwOYMEPfewapZ68k4g1AAkU1d8mtyNk0WEaHJo8xmZen8yEPOvVMbQ4maB3JkkxpJ47JdhIyMFe4A2I3w/yIffkRR5hrmYo99qTVKX2aa+yN+kY2/R+PCl+3dw9iG2v9w3XZsxU/yanAyyvl21ylXCVLmXVHQhHH462vZfqvkKuUT47,iv:4QvYsWYahFyBcyX0WuZAKdrsn2UKPVSmkUKUPpyU8ns=,tag:k2qSJEELAfTCZ0wkBdHEzw==,type:str]
    .htpasswd-gestione-sentieri: ENC[AES256_GCM,data:TX8iOKdjOz6kpIpL0VApFbq2NvygFP+ePpRMeABA6Ks1x2vRzaSrnRIlcoI7Nf7cv6VqsQ5XS0Qi90uKyKButjgR1HujDP7A2aV6Aiy+J952rNrJ8ov9imaYEwN8fDhlrJyzL+fZFSHl8y8YGEyQuXFYs8lo73RxjIcgJ2TciA6JIQ3DROqA82CXa9wqWepum3U4W/r2I7Tq6PnJv5UdGB/izz2HZuuQSk4VpDVJhmb5rH+OpyHLO2yKNGR3WW1PG1sOsnzI0vJqFrFqoMa00VH7diLGHTBBpmW4KIHnE1JuSDAbL56zPRdBalc1rxx8Lp9eIL8mZcRhNL4XCSkTN7LojiqQ4qZNcUHUybNFcsztXid3h5QpiF8f4z1CkyUrnSAjBJBh29PHsQ/+xbPiha5N+HknBBt3I5l6qjgi7e9R3wx1AsRTqHQrY3dLpSHqGs85dqvAhQpGI/ow0t5Ft64sI2mv9KOosmVye0EfjdeupzpXp5Ii369anXYgOFK8YcLx7t1GbQlAKg7hUg0L5tcsVY+280wn16kCRiKBRqdC/heF+mY9cajA8adEaF6hgU4=,iv:XucOfci9Atw8yV3OcF56VqQXACC+xolmxDYRtAUQCpc=,tag:6iSygPBxH78Xqi2Y5wFDJA==,type:str]
    .htpasswd-archivio-sentieri: ENC[AES256_GCM,data:G6855cK2tG25PZcajMXFZ5QR25sLn6byMC0g1J7x1pEAFUW5R1ROnKVYyFrbsVMq3Z25gBdiyrH6mVIC0Gb84CMlz0uLrUyRXfauGXrTzFYGe+nIxYSe8HhQ/vOZFVojdqkAd7nEokVC9Q+V40Oxp73AcLab1M1vyZcCGLHO55GUJHjEKPC+1gNlcMlB4nWWCyYPatYHUrtBHfYFKyyPLT8JtBQGTUOnfjj+9kUiJJa8fmOgLom0FAUlqSKt2csnA7UdHUPX3mfRhUNEhfWQfvs5NGfI/hcmv7heYa23KRdKe+0YjmBq1GHnRcrYDQv5UJUSNc5S+THwhHDv7IeGelnxNRcx2LHas45LU6CuAYPUDVXaB8Oa5n+jx8GYms9/CIjQJINlOEzNkRcMPOjodtCc4QGeVt3potc7gGh6KIW+G9YTKVeB4ManXUKdQ5JO36VRCBIXRyiggLJjbFB9+bxmT4+3qpKb4gLuzKcfoVRVPfZ/DmRi7NtHZjN8VvLmO/hEvcio3re972Dl1Tg+Aves4708IBk8SvO/CEy639c8OA4e+Nr1UJxbb6s4KIF2LKNq6uP7LdOwR0H5XPI1wbM6LALtMo9oqtCHPGoSLm9JdNxYFOU84I+JSYZ9STdMGcvaGn6ztjOavUbjRPI3BlskwJmcxlx7XSH+5TIYlCBLWNbPcXiJjUYVV9VS+5wcPw+V/7JPkEsD2oMyYE1mgVmSkjfp0SGbl2PoDdHIJYLtid/6U4qiFxmmGH8amSYght5IDVqn,iv:v1KIC6jsAn65blBr2jdIe2dQQ7MUx0Dp88AJ6/43/2I=,tag:rpLxI1zBx5RG7LOcCBSeSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaDB5M1ErejNKWWJWYnl4
            cGlrKzNvS2xQYjFjclRidmFsZjFVSXVpUGxNCkFxL2NRUmhseDlNSWM0RjhUeEN0
            aVFDRXZMTjlWZG1kQUdTUENSWXlGRk0KLS0tIGpqVjNwSm51OWU0cURGMGc3TFhG
            NVdQSlkxdzRpTWtMdjZJKysxQmRYL00K3cBuKCqbgreDyUJKVu9uP6o+xcDGA0f3
            N2RFUF25mqWpFZtOfJQF0kJESiE+jksNSWjQ9zkKp1g6ZiLItnehcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-09-08T11:10:20Z"
    mac: ENC[AES256_GCM,data:eOioHMiaZJ72F6hHV0OyRTN4xFqXtK468Nzl/1LKHO1Hh1gM2IYJoub5sIMwkz+bbqdZOyTiJSQIxdv3K6kdJVcl4iSYe7j0itf9NAEessB5StAQsl8FF7Hf08WiC63Z4VtP4IrercP3ZSeLVEzmxJs4m2gz0NQG8dqdm2ddciA=,iv:UPfDmfrLsAZypL+kNqYD4AsxDqkSRaGAqMwjtVAYeys=,tag:hYQtzBz61M7XDNpYhZKt7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
---
apiVersion: ENC[AES256_GCM,data:ki0=,iv:HMJtqrFTnEDDLP7+H5/NxqhV+zk71GIYGdydRC90gMI=,tag:MKRdj5TrwUtIHtL1LBv9Iw==,type:str]
kind: ENC[AES256_GCM,data:edXInQCF,iv:Vh9DHJ4g9mdHxYAAeY6hlJYJblENJjR4eVo+OLrIRV0=,tag:RIxGMOwdm6ZCvNMLohX19g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nz8sc+OdgajtXPpWZd5SFaB4,iv:w3zbaucpnrHlPKHEAcQgn8hESY+zyH5muvNYSKU52B8=,tag:z9F2j2CTs3XP3AEsNiEN8Q==,type:str]
    namespace: ENC[AES256_GCM,data:vuZ2zNbUeJvAmYq7NIU0,iv:AuIaZfbSMLkFYyYzmi9Vc8Tvm1jGJj6d7bVS68fGrKw=,tag:JQJK8cUDWKhvlVkh7Pc8lQ==,type:str]
type: ENC[AES256_GCM,data:4H8qwS7x,iv:fQgjDjoJbJzyu01K38TzygPmrBhA44+YwR7d5HsAbYw=,tag:bJrPPX2yB/EU/kIrm/npUQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:D34RNSK7AGg=,iv:hLUbwbY8JykDcGrercTWn1fgVbYr1Rw43w4a5vVAuAE=,tag:As5CCaSwLjzdh3nvMOCIdg==,type:str]
    password: ENC[AES256_GCM,data:kXRWjNfmDOo=,iv:4r6vG2uRPhgTTJfCdPFFcmb0k/80Ghwz/VPUVcOhbcw=,tag:qYNRxIjO4z/WfkOKIDfCtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaDB5M1ErejNKWWJWYnl4
            cGlrKzNvS2xQYjFjclRidmFsZjFVSXVpUGxNCkFxL2NRUmhseDlNSWM0RjhUeEN0
            aVFDRXZMTjlWZG1kQUdTUENSWXlGRk0KLS0tIGpqVjNwSm51OWU0cURGMGc3TFhG
            NVdQSlkxdzRpTWtMdjZJKysxQmRYL00K3cBuKCqbgreDyUJKVu9uP6o+xcDGA0f3
            N2RFUF25mqWpFZtOfJQF0kJESiE+jksNSWjQ9zkKp1g6ZiLItnehcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-09-08T11:10:20Z"
    mac: ENC[AES256_GCM,data:eOioHMiaZJ72F6hHV0OyRTN4xFqXtK468Nzl/1LKHO1Hh1gM2IYJoub5sIMwkz+bbqdZOyTiJSQIxdv3K6kdJVcl4iSYe7j0itf9NAEessB5StAQsl8FF7Hf08WiC63Z4VtP4IrercP3ZSeLVEzmxJs4m2gz0NQG8dqdm2ddciA=,iv:UPfDmfrLsAZypL+kNqYD4AsxDqkSRaGAqMwjtVAYeys=,tag:hYQtzBz61M7XDNpYhZKt7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
