---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentieri-webapp-download
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/www/download
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download
  namespace: sentieri-webapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sentieri-webapp-download
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archivio-foto
  namespace: sentieri-webapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
