apiVersion: ENC[AES256_GCM,data:HoA=,iv:YEfnGcsaQQ8PcOh/SZJHlgAfVHwkV+eFx3+xZGXHFc0=,tag:p+9WgwPr43lchAriivWmXg==,type:str]
data:
    passphrase: ENC[AES256_GCM,data:Y5u3b3aBWYPYksH2BuWVuyolmrxIwiH3Okrf7u49c3AIu1XsaZK4gXj1lGPb/hKfMFOvT5RT9OFoum9Cet2k8iFqvI8l5yR0IHZ4ozua9SQiBQc3Fi0l3g==,iv:ln5evUQcHkzqYzd+luM7g9JL1UKnxuqII9/Rj9VpyBk=,tag:CJsY2SC5nteMiauoFhV33A==,type:str]
kind: ENC[AES256_GCM,data:U+0QTfqf,iv:1cDLfbsC1VDZq2dNW2S8GYp2Ox/cJP/+0EZOn6DXkuM=,tag:4drVGn75plHx+9YC+l0GfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PiYmbLQSmOtMPtewoxrCXqJloYU=,iv:zrvdd4kD/qltX1hXAaaQF6/cwrUgHlg1zMh86kixf9k=,tag:oMHgc1s9H74O9RMbaqU/Tw==,type:str]
    namespace: ENC[AES256_GCM,data:HwrF/JNh,iv:R/BKLudd0MKQh0gL4dOyzHoRuSxfFvAzGAY0MKDgqBE=,tag:1y0Iu54sBMAAhMvW71FyMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSXJ3a3MxWDNCa0ZCekFD
            Ukk5SkRoS1dFbHZ6dVJZOXpsaFNFb2dDQkNvCnV4RjQ2Yklma2VVUldHN0E2UnNr
            OTFhbm5YTk5EUklMZzltNy8zMkxIZDQKLS0tIDlRZWpvSG5PUmMrYjFZTmNXQmFW
            YWZuS1pFTnBnY09rTWs0TEJRYmNkUDQKXJrQYWqyOWWBWGgNFpovpVsDP2Q6MFTM
            5Su8caPZr0IOZ7KILtj49zvvV/DtMKitxhNYY1VC5Szf0bI79t880g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-09-07T06:01:03Z"
    mac: ENC[AES256_GCM,data:VzOOuwl7Hg1zUHw5FzSllt3w2RpiNcDcLM9zONqQi8tuTEcvP9asOlAVV85mTNh40NHdDi67DhPEqPdMnaVgT0VEb3ENiAWsoqyfQIogA+vmnwzW8zVRV/UOQMSCh0+Zv/+7zd0Xv/Fj2Kllk6waV3g/dSDvOL1OXTlF09G/E14=,iv:2KSF07bx4jdwIdYVGXcVc9coWgFEkTeMQ7n4vqQGIxE=,tag:+u8pyol/gjKf9tIlpCSUFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
