apiVersion: ENC[AES256_GCM,data:QuY=,iv:yEmdFWQrZ01Ir+6YBJ16ZICb1si8wg1FJdJFb5ZynGc=,tag:gdpHVat07jBI4by25KG0Qw==,type:str]
kind: ENC[AES256_GCM,data:+P8JL7FL,iv:5Km/d3cjOddVW4j/Vh7uuYWxASAnMeEUW1INVeaejHA=,tag:nQhzNfiIm4WMqLbpaTLF8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:64bK4bAUXnsdHMIlhdSadqeu,iv:+FfojFUzxLHBS8wfcaD5+TKPKA4XRmhFMcWHKIGKwVg=,tag:SvVQj4w/OXFIA15++udTlg==,type:str]
    namespace: ENC[AES256_GCM,data:QEHyWVxZ,iv:xlxgv2jBfRvdNKwB/3yfGaq6rhAeUpcfFvJd8m6LtL8=,tag:dSBzvWBbqf6/ebh2g1bjSQ==,type:str]
type: ENC[AES256_GCM,data:jQG6Gps0,iv:D3UWxL/4A6uxo0LU4VqRw9uDRbHfbh1BYdQfHHNgMmo=,tag:6xWEPON5+N7Fi7WRneDRVw==,type:str]
stringData:
    source-username: ENC[AES256_GCM,data:Sc40p0M9lCo=,iv:+RAuD8T/lvoO5PxQFKtYuqR9hIEWS+Uf7Jfl9/RDjQA=,tag:JAsw5xFtu3rV1Kv96L53eg==,type:str]
    source-password: ENC[AES256_GCM,data:c9iieVeXPpE=,iv:Dap1+56E7eLV9TMhRbg0tbl+eDRfIO7iITsJGt/AmTk=,tag:+w0X3VQI1TnJxEDf8TAoGQ==,type:str]
    restore-username: ENC[AES256_GCM,data:/Vra3WXPRt8=,iv:JIQTGOA2Ez6aKqWzXZMRXUEL4LNNOE8AoJrDUwXHTUY=,tag:gpzhMayNz6FWMAmxyVFnJw==,type:str]
    restore-password: ENC[AES256_GCM,data:CAFWXpW1dMA=,iv:HKexKctkNJ3s5pldVMRmNNb+SVXDDHz7n3vn1YizDWQ=,tag:VjelD2HbTr8JCfTcAPy2aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWjVKOWE5K29vL3NVRWZ5
            OTZ5VlZERXpXRW9iQ3FJZUlhVjBZT09WMDJrCnV3SHFwSHRFQzBhMzlYM2J5cXpC
            OTVYL2JNTnlIYWNtQnFwZUR2dFhwTmcKLS0tIDM5R05rZzY2WUo3ZGttQjh3Z3lr
            Y3JZbUF3WmM4VXEreTZqWUFvcW9oZUEKvvZSvKXHlQ6c27PtWmpWzI5RagNr03y3
            raLPPYO+R+NRsko/0ZoqewVIjIZn2yBR3/8xzijY9mwxolutHDG38A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-09-07T13:35:25Z"
    mac: ENC[AES256_GCM,data:ZeLzWF3xYHI0NLt1nXqblpKHgw7f/UF2IZXdBN37AszGLbPAc8NrACZNAQoB7ugC3e0YSLzA8i3i+Kifi41mTgpJWF9K9J+9GVtG9BDMZcz3Dtf4qb2tvg0My4HhFq07rDYFhlcbURNS1MzCMMeL0mI/mErcg1Tw0sC1LuamGz4=,iv:kqLx1vcx2QanLg7sriWv8RFRMwA18YBomtJzZKV+Dgk=,tag:LORIRFBa37q2WI7coOJFVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
