---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./borgmatic-ssh.secret.yaml
  - ./borgmatic-passphrase.secret.yaml
  - ./borgmatic-database.secret.yaml
  - ./config.yaml
  - ./resources.yaml
