apiVersion: ENC[AES256_GCM,data:6CQ=,iv:3fv2JxLc5WUAOL9pcnuBLSI4BxEb7sho1XpEUG2zsLk=,tag:khjm7GPsCFJwLizxOH64Ig==,type:str]
kind: ENC[AES256_GCM,data:OZ8DrCB2,iv:+8hMR3jB7RiF5A4DUKK3uue+nUXssPU3gEkmtm3U0VM=,tag:sTX5oEHH1J7O4KxQ619WAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2V0xpugZuMTJDhk=,iv:DH6ZvGXxIe6ExTSrhjoSMWlW92kNx3l56yW5kzyk3dA=,tag:EetVBjJ86qcru+QdyM24cQ==,type:str]
    namespace: ENC[AES256_GCM,data:yrUhAQnsA/Nc8HA=,iv:0/9yd/wP1cnoTLqm5kbR1SPJiyU0VcTzL+m06MrwoqI=,tag:ODZRBlo/v2QIGwRBgYPVTw==,type:str]
type: ENC[AES256_GCM,data:r1FohjUC,iv:V+YSPQOspC6dRm9BVxulzsAVxsQ1DhnepNMzqWfTH0g=,tag:zHWk02jUvNMDnk5cw0CKHg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:G5jcanWPypM=,iv:g9T6GQc+klbYpVdtiNjY/QaDZHAO8UC94FLrtp9tyXU=,tag:P0SYafwDE9hOSJcSPv3fDg==,type:str]
    password: ENC[AES256_GCM,data:GY7hHmFbkB8=,iv:tlpQLvc1TMgpUTfCOykn2+Du28xcXCee62XPhceY8vk=,tag:EF2rBAdsMrHkmGRaFieaCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUytOa0pJeFp0aHBobU9p
            TWVVeWVVT2J2Zk1aS3E0NWg0cVJNLytRWkU4CnJlTllaWlZMU21rYkxXUzRWZzI4
            VmxOdmxkb3djM1ZSbWlXbEsxZS94TGsKLS0tIHVqeUgzOFJmaFJncFJNTkdxdVpE
            L1diNGQwMXpTL0ZBa2tmTVZWQURuOHcKl1Hof1dayh02P19x0jrPyx98p0EGRtJq
            GVSKR1p+V/oMspdGloD64tknWKGkBAHMTcqcAug/r97XBPxNVPV4Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-09-06T17:14:38Z"
    mac: ENC[AES256_GCM,data:iKVQNbdX1Y5vcUr4cmt1Jr1B2mRyJNrvN1vm5jMMzCNvo4mHmTX9m0wrFVA0dVjrnfMKO5pwqkjMdQKZzsrozAeVpSZkU30Ai8e0q9lWu6+OPOx8/btYsjhTWF8Nn5hu38sKvsFSeyUxgDBeuqYf42/0hFpaYW/cRnkdgroj9gA=,iv:HtaTcoIB3PfkCekOnkHLMzdUUVtFNwP+KmGWQuXY4Ps=,tag:hahKM0XIkImMIwBJdQKilg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
