apiVersion: ENC[AES256_GCM,data:TcI=,iv:b5Cs/h9UA36Z/heDN2/bEgZ0Q5yWEIX6rARo0Nc8Tlk=,tag:5w7AytqkN32cirSe48aqgQ==,type:str]
kind: ENC[AES256_GCM,data:iyuMWTgE,iv:B33y9tr99ymhHu3UGQI2cVvA8WFEp0csjaKIaJNhWqU=,tag:+Me+ki8ngYLucV/DIZ5VcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zPDdtv+yGIkypMHkj70habzbTus=,iv:PA1HOqgkOx07ft+zxWMH97he18ailbdnDP6ref+VaUQ=,tag:l0BLewfqDSZQAOw5iZs8kA==,type:str]
    namespace: ENC[AES256_GCM,data:gOh+EMbE5AP8Jaos,iv:qH1E9ER/XVPsOnD0sNQ/cJB+7YXLMIFL5F4zuBvVoEc=,tag:IguNP4I/FMHJKk2dtNbM/g==,type:str]
type: ENC[AES256_GCM,data:pO6O/pYR,iv:NzW7Jdc29yeJ3AwLAFWpESgvpQFPBbPMWd498gOOTgY=,tag:ePLRHU/EccYuQcavzysa+A==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:FEuTcuZvNdHh8rWdBlFlIbiBtzXFvljmTZBq1GFl31PIhPj/eQy/cjSA4gTh8lb20EDWC7A=,iv:H2y2HGTqPMBBkq9I7Jmw+RhOSOQ99CbGBKQTOV5ZaWU=,tag:f7BKDaISPxxr5RDNhrpzIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRmJ4eE9ubisvNmxTS1Bj
            SVNIQzJqMVF6dVNpV2E4OVd4dmpqUnIrY2dZCmJ5RXI1UmM5NWc2UkxsY212N3hy
            M0FTdmtRbU94VW5ROGFFU09FSkxpeVEKLS0tIEtzYytDa3VvbDVXanIwOXFSUDVh
            STNvR3BKNzhPa3JlN0JnVzE2N2hUVTQKo9hyWewlspNKQWJAKZxbJKbPZCSoZ2sp
            3qVgdJt3Il/NZTDVc+TrAmfZugtkzvFBpoJb4v9iIrLBeAKZEdYaVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6 # pragma: allowlist secret
    lastmodified: "2026-09-02T16:32:30Z"
    mac: ENC[AES256_GCM,data:LtHMcVc7H1Jo77K6mSaUGtLFpWe114zxAAZs3IeTbARr3aJAVrsPN6jSraibD5gquLq7BPZzrzli09uI0PgYGG0KjET0jeWOe9wSxx//tU2BZw0EEHY1sNgRP1TWXER7wpTS2jh7K5piW6JLZctilfd9WZsYtiuSGdpbB3b/tl0=,iv:kUSVkYZTrrsx5vtVxjCYEhsFysq4WPbdMeEyoNnvhUU=,tag:cnU9NRS/ThKDOSmB95Y+gA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
