---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zot
  namespace: flux-system

spec:

  interval: 5m
  path: "./infrastructure/zot"
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - sources
