ihostname: kubesat0
manage_etc_hosts: true

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - bash-completion
  - ca-certificates
  - curl
  - nfs-common
  - open-iscsi
  - qemu-guest-agent
  - zfsutils-linux

timezone: Europe/Rome

users:
  - name: debian
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILO2ogG4ayFwoIJVBXZTQOZI7vTB8z03e1KG/z7zixRw giovanni@G3ARCH
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDvbRhcyUAotOfDG8HB98GrZgsBk0E4G66dcI4HKN/D1 pupillo@cntsrv1
    sudo: ALL=(ALL) NOPASSWD:ALL
