write_files:
    - path: ENC[AES256_GCM,data:f5BaCIHYt/NKrboDfjHq0DvhlE2v/I8iP0E861TqmwHmV6a6dwhVVb+6TcKGo1aZGzvZnpUqdKGR,iv:9WZXC/K1BUJlqLuIEVvXKVNSm58xSpu8mIvG6npvSy8=,tag:/XMzkyZkLd7fmrJtcR7UIg==,type:str]
      owner: ENC[AES256_GCM,data:XE2Pktel1jIj,iv:FVivFyM35qGe0Ppq3KpLeBu5y3pE9TdpbwnNMvfehuQ=,tag:4wFqanQmGhuSb1lyl1Flew==,type:str]
      permissions: ENC[AES256_GCM,data:nwV7NA==,iv:Yo2nlkkedt9bYZM2dAQxT+asIk/q3oh2DBKZNBjRvFE=,tag:f8f4412g6a1wR4ZjhBS0Nw==,type:str]
      content: ENC[AES256_GCM,data:DZs8p5PXJ6wOvlbfL9By5iV25puK8Xqfxcz2MwI9qIr2RPYrPjnDbJoBlN81M5MPXDM+lAikstjdRHcj5IvCB7PwpaEslmtN7ZlZC8Sf6/eENZS/AxVRbg0Luz0nf3d+UOH42lk462E39KzDZJNtbtyabYHfWbdrssZyA/r+XeKn/tOGqlHHBVBfj/M7s8wonacCe42TL2xkTChAsLloNWRMD0kNHNzL0A5j6JSvAYcbRC6W34ODB/k1Do+hIkIix3Z1eqwA+m4uessbvDxDJQE1g+VoafkRfOFadB47Q1bgfKgg5w8Vue0XpSAkJ2H2RHuj0E5KPwUVQTBCrOnlmIv4EMcxMYD/cZ4irnclXfqqYh3+lLUHtelRxkB3AaKaondekoflv0s/PzWtvJO3kvPEpNn81dZDwfzekXl5yGAQoDU9m3FuMoUyeybOQKznBWsJ1sQ1Y+WORfuadlMGbSs=,iv:9EWWc+em24RbDjse7nzpeIu8MjrpAM3Mhm38mOX1Xvw=,tag:11CCAh79T0rSLIayZt9WhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQy9kOEpWcU1sL2dCNXYw
            MzhOdHNrVHkvam1PWXRCWWJLbkdoaE5nbUV3CmJtTXU4aDJFQTlxK3NBc05aRVlt
            OUpQUVpxTE84THlwbGN2ZzZrRDk0RW8KLS0tIEwwbEtFYXI5ZEdFMGVkS09rQlVB
            SVY5QXpLeFV5R25MTmt1L1Y2aDdJL3MKMAtMYgK7EdDa5/Lp5bHdvIIscCL1E59x
            VsMc9qZu7Rk9cSJ2+hUntsJugpHNBL48Iop3Fz2zJTJ5BdqtxcZwJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gk7hl04yythddxc0wl9drsg6qp4lpv2tcemhcttlpy3kquaf793sfphf9e
    lastmodified: "2026-09-02T20:56:23Z"
    mac: ENC[AES256_GCM,data:4YOdrfREPcpL8Z7L8vHV+BvSHJd8agA/sb+GRPp0sJOPc0yKOxiaowXrsOmQEBOEIb0GDHlgTVWZeQNe6O0DnszImBeeiy9TNZk5vRKXKQbdZaWHv3NwX7EzK2b5dVm0ADWDKLPQCM33i/0HagEEwJYQw6knpJ4UutVCQx62LwM=,iv:ERyT3AcONGx6x85NSThPCI88qYYOy2ZJy5qjPi14Ubc=,tag:LCf3k/BKQhUKL8SU2m6U6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
