---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./github-ssh-sentieri.secret.yaml
  - ./build-aggiorna-sentieri.yaml
  - ./build-sentieri-webapp.yaml
