apiVersion: ENC[AES256_GCM,data:P8M=,iv:qlvplSbLTuEQnAbNunATpziD2rKXW1ao80NrfGttsDk=,tag:UTOeRXNp4hs+eu4V80ZJMg==,type:str]
kind: ENC[AES256_GCM,data:uHp+2bqk,iv:HQQiLkfCsEXJxqXFwjeBZhsiPhCtav1GbR3Asn0fI9Q=,tag:mobIWH5wANfFPkiaN6lpJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vIj2ig3L6m3zML3lXjtoRmc=,iv:eX8TtspSHXJjZvkyfOFxZoyQFLMfm6ezeRmxdJxkxt0=,tag:dPrqy8weeAIEVf+TWrey9Q==,type:str]
    namespace: ENC[AES256_GCM,data:FW+szizBvVImHMBBZZaU7IA=,iv:R5kcXYCkh5C/ChJSH1Vmaw/xREG7FrwX28CbgTVIW1k=,tag:BOQAh7VBUwkgJCd+zVfoqg==,type:str]
type: ENC[AES256_GCM,data:DPrCJG+Z,iv:FnLnavMMzw2F53zR75j5DgbhFoogguEUtlxP7nH3yQY=,tag:4q+kFrhwn/sGa4ChqrSuxg==,type:str]
stringData:
    piwigo-host: ""
    piwigo-user: ""
    piwigo-password: ""
    piattaforma-user: ""
    piattaforma-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK1ZuOUtYM0V1VzI4K01F
            K0xzRTFVRHBrcWp1RkpFd2lCWDUxOVZKMkhzCkJ4SkRNVjNacmMzMmZlbXRWNzNP
            U2FBemI4VFZlN1NkL0IyV0NnL0FrazAKLS0tIEVwZkNscUFZeFRRbHhmZ1ppWnFo
            NEtDQk9rMjVyZ0ZyOEVUekpNSXBYNWcKBivJSBS/gAtDBdKw3p/qSMJVkMAr9U4O
            kaOtsxPKT9d2Fq8J9cKk+yRXOK10Eqe5J2hbyvZl7HSJThryNihQhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-10-01T03:50:00Z"
    mac: ENC[AES256_GCM,data:2tIO6aXr+4MhSgYoqFZRACs0FyBR1hON6wLgN3Xteq4cRfVXwtnY87Mmo/MgeTEO3SzxHHyi9MKSmRfjbej0EH+4ma7CHEx8fpxx1+bOZEiWZ005m/p6P85ky4quPZaakCFxAqODmF4n7yY+6V5dOXjsroJm9pWZDh+AS9igt4Y=,iv:Hkn0+1Wsx8gXiO4ZVjT/ziZ4LZ48USAUph/GBL0Rujw=,tag:bhTSmFoqyTKKmpkVhXIxGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
