apiVersion: ENC[AES256_GCM,data:COM=,iv:IYjO6cShDsz8wC0uUvgMvrT2pB+uA9V+aCV9p/DYMW4=,tag:nRkqI5KR7ZZUYs1+H73CtQ==,type:str]
kind: ENC[AES256_GCM,data:m4O50NLy,iv:AbyvOgGHiAB2nTgElZIyudhdMWt1lLGjx5eRP6Rxt0s=,tag:8KZRkXYroiy6qh9q+v3yrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WllahXpQjpojXvWTeQYaK4lp,iv:EJMGc/q1AcfjOau8NyvH3bKzqy4RSSPE6rgAI/sRVnw=,tag:189Hhbz8tAcH5X4FBltrtw==,type:str]
    namespace: ENC[AES256_GCM,data:Rl4oWIwdDOT6ZEuZ9FVhyPk=,iv:xEQ+4GcNFAlR0Wp57jkbKyCv0P2O7vQ85/AwBgiO5A8=,tag:MBLkmQ/nHzO6fFLWXWOeww==,type:str]
type: ENC[AES256_GCM,data:zCfg7d31,iv:86ftqlVC+gtLLC8YijK0q/dCv8Rgk3FdibMizxCgbV4=,tag:ca6CZ9TdNUDXWnCMsFYvww==,type:str]
stringData:
    username: ENC[AES256_GCM,data:aWUYYiZQFbI=,iv:yNhUM4uNQcX41wsKXDe9UePBiTA5mDN2kvXadcK9OjE=,tag:Bo2clma3BUCujairnUCdrw==,type:str]
    password: ENC[AES256_GCM,data:upbUFuVqC9A=,iv:NUSNXwm2zHDKGL+E4VysMo49YiJeBrES3hBUL1xyyfg=,tag:lVcI6aENoqPv7nHeVHZP4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybUZ4aUtXTjF3SjJVdTJk
            NDB2aVBzRm92USttcityQjR6VE1qL3plZUd3CityaFNYMUo3VWM2NGlxYUE5TWcv
            R0RtcEVGeW5QTHlRWDVDbWFnNkltMUUKLS0tIGlRQzhDVkxqdnhyK2hqbEFlNm0x
            cUZUbVpZcDRRYlVqbW14ZXhUN0hhd2MKiix09sUF76weDEc+n0tEjQJpi/lLWJhj
            GtU363LlXNJH9d61vkROmFdRI3IhVjyzZGCo55NGqT7uCE/AMc+cLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kc0uu5rykj4vcml2k4fypnzdnpjjdjg3tpvm5l4h7y7lsnrreftslljuy6
    lastmodified: "2026-10-01T03:50:06Z"
    mac: ENC[AES256_GCM,data:JkNk0jkUmcMtEmH8bj+AZ9YghDtxH0mkQHC+hXmwFvyuc85az2aNtLX/qMNfny/hEHtcx8skx5CUMtePa3PhCZcE6cIbRqrdf/0mEpr9RGTG220pancz49BQaIQoofpsHS0RupAJLK0MPGpXMr6Q8EIPUiZIFhdd3r2yws/aCw4=,iv:XE90fRWBOMpglMIoQL9ebntrSjfk3sEh0z6i8a/vFNU=,tag:84F+ac4UrgDkBijMzDxljQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
