---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aggiorna-sentieri-download
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /opt/www/download
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aggiorna-sentieri-download
  namespace: aggiorna-sentieri
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: aggiorna-sentieri-download
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aggiorna-sentieri-archivio-foto
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /opt/archivio-foto
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archivio-foto
  namespace: aggiorna-sentieri
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: aggiorna-sentieri-archivio-foto
  resources:
    requests:
      storage: 1Gi
